title: Saurabh Harak Portfolio 
description: Full Stack Developer turned Data Engineer ğŸš€ | Python Developer ğŸ | Full Stack Background ğŸ’»| 3+ Years Experience â±ï¸| Let's dive into the world of data-driven possibilities! ğŸ“ˆğŸ“ŠğŸ’¡

show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
