title: Saurabh Harak Portfolio 
description: Data Engineer turned Data Scientist ğŸš€ | Python Developer ğŸ | Full Stack Background ğŸ’»| Transforming Data into Insights ğŸ“Š | 3+ Years Experience â±ï¸| Let's dive into the world of data-driven possibilities! ğŸ“ˆğŸ“ŠğŸ’¡

show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
